export const checkedCompaniesActionTypes = {
  ADD_COMPANY: 'ADD_COMPANY',
  DELETE_COMPANY: 'DELETE_COMPANY',
  ADD_ALL_COMPANIES: 'ADD_ALL_COMPANIES',
  DELETE_ALL_COMPANIES: 'DELETE_ALL_COMPANIES',
}
