export const checkedCoworkersActionTypes = {
  ADD_COWORKER: 'ADD_COWORKER',
  DELETE_COWORKER: 'DELETE_COWORKER',
  ADD_ALL_CHECKED_COWORKERS: 'ADD_ALL_CHECKED_COWORKERS',
  DELETE_ALL_CHECKED_COWORKERS: 'DELETE_ALL_CHECKED_COWORKERS',
}
