export const checkedCompaniesActionTypes = {
  ADD_COMPANIE: 'ADD_COMPANIE',
  DELETE_COMPANIE: 'DELETE_COMPANIE',
  ADD_ALL_COMPANIES: 'ADD_ALL_COMPANIES',
  DELETE_ALL_COMPANIES: 'DELETE_ALL_COMPANIES',
}
