export const companiesActionTypes = {
  GET_COMPANIES: 'GET_COMPANIES',
  CHECK_COMPANY: 'CHECK_COMPANY',
  CHECK_ALL_COMPANIES: 'CHECK_ALL_COMPANIES',
  UNCHECK_ALL_COMPANIES: 'UNCHECK_ALL_COMPANIES',
  ADD_NEW_COMPANY_TO_COMPANIES: 'ADD_NEW_COMPANY_TO_COMPANIES',
  DELETE_COMPANY_FROM_STORE : 'DELETE_COMPANY_FROM_STORE',
  UPDATE_COMPANY: 'UPDATE_COMPANY',
}
