export const companiesActionTypes = {
  GET_COMPANIES: 'GET_COMPANIES',
  CHECK_COMPANIE: 'CHECK_COMPANIE',
  CHECK_ALL_COMPANIES: 'CHECK_ALL_COMPANIES',
  UNCHECK_ALL_COMPANIES: 'UNCHECK_ALL_COMPANIES',
}
