export const coworkersActionTypes = {
  GET_COWORKERS: 'GET_COWORKERS',
  CHECK_COWORKER: 'CHECK_COWORKER',
  CHECK_ALL_COWORKERS: 'CHECK_ALL_COWORKERS',
  UNCHECK_ALL_COWORKERS: 'UNCHECK_ALL_COWORKERS',
}
