export const coworkersActionTypes = {
  GET_COWORKERS: 'GET_COWORKERS',
  CHECK_COWORKER: 'CHECK_COWORKER',
  CHECK_ALL_COWORKERS: 'CHECK_ALL_COWORKERS',
  UNCHECK_ALL_COWORKERS: 'UNCHECK_ALL_COWORKERS',
  ADD_NEW_COWORKER_TO_STORE : 'ADD_NEW_COWORKET_TO_STORE',
  DELETE_COWORKER_FROM_STORE: 'DELETE_COWORKER_FROM_STORE',
}
