export const selectedCoworkersActionTypes = {
  ADD_COWORKERS: 'ADD_COWORKERS',
  DELETE_COWORKERS: 'DELETE_COWORKERS',
  ADD_ALL_COWORKERS: 'ADD_ALL_COWORKERS',
  DELETE_ALL_COWORKERS: 'DELETE_ALL_COWORKERS',
  ADD_COWORKER_TO_TABLE : 'ADD_COWORKER_TO_TABLE',
  DELETE_COWORKES_FROM_TABLE : 'DELETE_COWORKES_FROM_TABLE',
}
