export const selectedCoworkersActionTypes = {
  ADD_COWORKERS: 'ADD_COWORKERS',
  DELETE_COWORKERS: 'DELETE_COWORKERS',
  ADD_ALL_COWORKERS: 'ADD_ALL_COWORKERS',
  DELETE_ALL_COWORKERS: 'DELETE_ALL_COWORKERS',
}
